// Product
export const ADD_PRODUCT = "ADD_PRODUCT";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const COMMENT_LOADING = "COMMENT_LOADING";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_LIKE = "UPDATE_LIKE";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

// Modal
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_MODAL_LOADING = "TOGGLE_MODAL_LOADING";
export const TOGGLE_MODAL_ERROR = "TOGGLE_MODAL_ERROR";
export const TOGGLE_MODAL_CLEAR = "TOGGLE_MODAL_CLEAR";

// Alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Auth Registration
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const GUEST_LOADED = "GUEST_LOADED";
export const ADMIN_LOADED = "ADMIN_LOADED";

// Auth Login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

// Avatar
export const UPDATE_AVATAR = "UPDATE_AVATAR";
export const UPDATE_AVATAR_LOADING = "UPDATE_AVATAR_LOADING";
export const UPDATE_AVATAR_ERROR = "UPDATE_AVATAR_ERROR";

// Account Delete
export const ACCOUNT_DELETE = "ACCOUNT_DELETE";

// Secrete Key
export const jwtSecrectKey = "onik7890";
export const adminKey = "1234";

// Cart
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_LOADING = "ADD_TO_CART_LOADING";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS";
export const REMOVE_CART_SUCCESS_LOADING = "REMOVE_CART_SUCCESS_LOADING";
export const REMOVE_CART_ERROR = "REMOVE_CART_ERROR";
export const REMOVE_FROM_CART_ERROR = "REMOVE_FROM_CART_ERROR";
export const REMOVE_FROM_CART_LOADING = "REMOVE_FROM_CART_LOADING";
export const TOGGLE_CART_ERROR = "TOGGLE_CART_ERROR";
export const TOGGLE_CART_LOADING = "TOGGLE_CART_LOADING";
export const TOGGLE_CART_SUCCESS = "TOGGLE_CART_SUCCESS";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_SUCCESS_ERROR = "GET_CART_SUCCESS_ERROR";
export const GET_CART_SUCCESS_LOADING = "GET_CART_SUCCESS_LOADING";
export const CLEAR_CART_FROM_STORE = "CLEAR_CART_FROM_STORE";
export const CLEAR_CART_FROM_STORE_LOADING = "CLEAR_CART_FROM_STORE_LOADING";
export const CLEAR_CART_FROM_STORE_ERROR = "CLEAR_CART_FROM_STORE_ERROR";

// Profile
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const ADD_PROFILE = "ADD_PROFILE";
export const DELETE_PROFILE = "DELETE_PROFILE";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const ADD_ORDER = "ADD_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const ADD_PAYMENT = "ADD_PAYMENT";
export const DELETE_PAYMENT = "DELETE_PAYMENT";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const TOGGLE_ADDRESS = "TOGGLE_ADDRESS";
export const TOGGLE_ORDER = "TOGGLE_ORDER";
export const TOGGLE_PAYMENT = "TOGGLE_PAYMENT";
